import { createClient, type SupabaseClient } from 'npm:@supabase/supabase-js@2'

const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-aezakmi-station-id, x-aezakmi-station-token','Access-Control-Allow-Methods':'POST,OPTIONS'}
function preflight(req:Request){if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});return null}
function json(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{...corsHeaders,'Content-Type':'application/json'}})}
function fail(error:any,fallback='Request failed.'){const status=Number(error?.status||500);return json({success:false,code:error?.code||'SERVER_ERROR',error:status>=500?fallback:(error?.message||fallback)},status)}
async function sha256(value:string){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function namedKey(envName:string){const raw=Deno.env.get(envName)||'';if(!raw)return'';try{const parsed=JSON.parse(raw);if(parsed&&typeof parsed==='object')return String(parsed.default||Object.values(parsed)[0]||'')}catch{}return''}
function projectUrl(){const v=Deno.env.get('SUPABASE_URL')||'';if(!v)throw Object.assign(new Error('SUPABASE_URL unavailable.'),{status:500});return v.replace(/\/+$/,'')}
function secretKey(){const v=Deno.env.get('SUPABASE_SECRET_KEY')||namedKey('SUPABASE_SECRET_KEYS')||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!v)throw Object.assign(new Error('Supabase privileged key is unavailable.'),{status:500});return v}
function adminClient(){return createClient(projectUrl(),secretKey(),{auth:{persistSession:false,autoRefreshToken:false}})}
async function stationAuth(req:Request,admin:SupabaseClient){const id=String(req.headers.get('x-aezakmi-station-id')||'').trim(),token=String(req.headers.get('x-aezakmi-station-token')||'');if(!id||!token)throw Object.assign(new Error('Customer Station credentials are required.'),{status:401,code:'STATION_AUTH_REQUIRED'});const hash=await sha256(token);const{data,error}=await admin.from('station_devices').select('id,organization_id,branch_id,local_station_id,station_name,realtime_topic_key,status,revoked_at,cloud_last_seen_at').eq('id',id).eq('device_token_hash',hash).maybeSingle();if(error)throw error;if(!data||data.revoked_at)throw Object.assign(new Error('Customer Station credential is invalid or revoked.'),{status:401,code:'STATION_AUTH_INVALID'});const{data:org,error:orgError}=await admin.from('organizations').select('lifecycle_status').eq('id',data.organization_id).maybeSingle();if(orgError)throw orgError;if(!org||!['active','grace_period'].includes(String(org.lifecycle_status||'active')))throw Object.assign(new Error(org?.lifecycle_status==='terminated'?'This business has been terminated.':'Cloud access for this business is suspended. Use Café Edge fallback.'),{status:403,code:org?.lifecycle_status==='terminated'?'BUSINESS_TERMINATED':'BUSINESS_SUSPENDED'});return data}
async function mirrorStationStateToEdge(admin:SupabaseClient,station:any,command:any,result:any){if(!['lock','unlock','reboot','shutdown'].includes(String(command.command)))return;const{data:edge,error}=await admin.from('edge_servers').select('id').eq('branch_id',station.branch_id).is('revoked_at',null).order('last_seen_at',{ascending:false}).limit(1).maybeSingle();if(error||!edge)return;await admin.from('cloud_commands').insert({organization_id:station.organization_id,branch_id:station.branch_id,edge_id:edge.id,station_id:station.local_station_id,command:'station_state',payload:{stationCommandId:command.id,command:command.command,result:result&&typeof result==='object'?result:{}},expires_at:new Date(Date.now()+120000).toISOString()})}

Deno.serve(async req=>{const pre=preflight(req);if(pre)return pre;try{const admin=adminClient(),station=await stationAuth(req,admin),body=await req.json().catch(()=>({})),action=String(body.action||'heartbeat'),now=new Date().toISOString();
  if(action==='heartbeat'){
    const recovered=Boolean(body.recoveredFromFallback);const patch:any={status:'online',cloud_last_seen_at:now,updated_at:now};if(recovered)patch.last_sync_restored_at=now;if(body.usedFallback)patch.last_fallback_at=now;await admin.from('station_devices').update(patch).eq('id',station.id);await admin.from('branch_stations').update({station_device_id:station.id,cloud_last_seen_at:now,cloud_connection_status:'online',updated_at:now}).eq('branch_id',station.branch_id).eq('local_id',station.local_station_id);return json({success:true,station:{id:station.id,organizationId:station.organization_id,branchId:station.branch_id,localStationId:station.local_station_id,name:station.station_name},serverTime:now})
  }
  if(action==='poll'){
    await admin.from('station_commands').update({status:'expired',acknowledged_at:now,result:{error:'Station command expired before delivery.',code:'COMMAND_EXPIRED'}}).eq('station_device_id',station.id).eq('status','queued').lte('expires_at',now);const{data,error}=await admin.from('station_commands').select('id,command,payload,status,requested_at,expires_at').eq('station_device_id',station.id).in('status',['queued','running']).gt('expires_at',now).order('requested_at',{ascending:true}).limit(20);if(error)throw error;return json({success:true,commands:data||[],serverTime:now})
  }
  if(action==='ack'){
    const commandId=String(body.commandId||''),status=String(body.status||'');if(!commandId||!['running','completed','failed'].includes(status))return json({success:false,code:'ACK_INVALID',error:'Command id and valid status are required.'},400);const{data:command,error:commandError}=await admin.from('station_commands').select('id,command,status,station_device_id').eq('id',commandId).eq('station_device_id',station.id).maybeSingle();if(commandError)throw commandError;if(!command)return json({success:false,code:'COMMAND_NOT_FOUND',error:'Station command was not found.'},404);if(['completed','failed','expired'].includes(command.status))return json({success:true,command:{id:command.id,status:command.status},duplicate:true});const allowed=command.status==='queued'?['running','failed','completed']:command.status==='running'?['completed','failed']:[];if(!allowed.includes(status))return json({success:false,code:'COMMAND_STATE_CONFLICT',error:`Command cannot move from ${command.status} to ${status}.`},409);const result=body.result&&typeof body.result==='object'?body.result:{};const patch:any={status,result};if(status==='completed'||status==='failed')patch.acknowledged_at=now;const{error:updateError}=await admin.from('station_commands').update(patch).eq('id',command.id).eq('status',command.status);if(updateError)throw updateError;if(status==='completed')await mirrorStationStateToEdge(admin,station,command,result);return json({success:true,command:{id:command.id,status}})
  }
  return json({success:false,code:'INVALID_ACTION',error:'Unsupported station runtime action.'},400)
}catch(e){return fail(e,'Customer Station cloud runtime failed.')}})
