import crypto from 'node:crypto';import jwt from'jsonwebtoken';import{db,nowIso}from'../db/connection.js';import{env}from'../config/env.js';const enc=v=>encodeURIComponent(String(v??''));const A={
'station.create':a=>['POST','/pcs',a],'station.update':a=>['PATCH',`/pcs/${enc(a.id)}`,a.patch||{}],'station.delete':a=>['DELETE',`/pcs/${enc(a.id)}`],'station.reset_pairing':a=>['POST',`/pcs/${enc(a.id)}/reset-pairing`,{}],
'session.start':a=>['POST','/sessions/start',a],'session.end':a=>['POST',`/sessions/${enc(a.id)}/end`,a.body||{}],'session.refund':a=>['POST',`/sessions/${enc(a.id)}/refund`,{}],'session.time_adjust':a=>['POST',`/sessions/${enc(a.id)}/time-adjustments`,a.body||{}],
'member.create':a=>['POST','/members',a],'member.update':a=>['PATCH',`/members/${enc(a.id)}`,a.patch||{}],'member.delete':a=>['DELETE',`/members/${enc(a.id)}`],'member.wallet_set':a=>['PATCH',`/members/${enc(a.id)}/wallet`,{balance:a.balance}],'member.wallet_adjust':a=>['POST','/wallet/adjustments',{memberId:a.id,amount:a.amount,type:a.type||'adjustment'}],'member.wallet_transfer':a=>['POST',`/members/${enc(a.id)}/wallet-transfers`,{destinationMemberId:a.destinationMemberId,amount:a.amount}],'member.time_transfer':a=>['POST',`/members/${enc(a.id)}/session-time-transfers`,{destinationMemberId:a.destinationMemberId,seconds:a.seconds}],'member.session_topup':a=>['POST',`/members/${enc(a.id)}/session-topup`,{ratePlanId:a.ratePlanId,amount:a.amount??null}],
'rate.create':a=>['POST','/rate-plans',a],'rate.update':a=>['PATCH',`/rate-plans/${enc(a.id)}`,a.patch||{}],'rate.delete':a=>['DELETE',`/rate-plans/${enc(a.id)}`],
'topup.approve':a=>['PATCH',`/top-ups/${enc(a.id)}/approve`,a.body||{}],'topup.reject':a=>['PATCH',`/top-ups/${enc(a.id)}/reject`,a.body||{}],'extension.confirm':a=>['POST',`/session-extensions/${enc(a.id)}/confirm`,a.body||{}],'extension.reject':a=>['POST',`/session-extensions/${enc(a.id)}/reject`,a.body||{}],
'announcement.create':a=>['POST','/announcements',a],'announcement.update':a=>['PATCH',`/announcements/${enc(a.id)}`,a.patch||{}],'announcement.delete':a=>['DELETE',`/announcements/${enc(a.id)}`],'settings.update':a=>['PATCH','/settings',a],'billing.session':a=>['PATCH','/billing-policy/session',a],'billing.postpaid_rate':a=>['PATCH','/billing-policy/postpaid-rate',a],'support.resolve':a=>['PATCH',`/support/${enc(a.id)}/resolve`,a.body||{}],'feedback.status':a=>['PATCH',`/feedback/${enc(a.id)}/status`,{status:a.status}],'feedback.restore':a=>['POST',`/feedback/${enc(a.id)}/restore`,{}]};
function token(){const u=db.prepare("SELECT id,must_change_credentials FROM users WHERE role='admin' AND is_active=1 ORDER BY created_at LIMIT 1").get();if(!u)throw Object.assign(new Error('Local Admin account unavailable.'),{code:'LOCAL_ADMIN_MISSING'});if(u.must_change_credentials)throw Object.assign(new Error('Finish local Admin credential setup first.'),{code:'LOCAL_ADMIN_SETUP_REQUIRED'});const id=crypto.randomUUID(),jti=crypto.randomUUID(),now=nowIso(),exp=new Date(Date.now()+120000).toISOString();db.prepare('INSERT INTO auth_sessions(id,user_id,jwt_id,pc_id,client_ip,created_at,last_seen_at,expires_at) VALUES(?,?,?,?,?,?,?,?)').run(id,u.id,jti,null,'127.0.0.1',now,now,exp);return{id,t:jwt.sign({sub:u.id,role:'admin',memberId:null,pcId:null,jti},env.jwtSecret,{expiresIn:'2m'})}}
async function call(spec,id){const s=token();try{const[m,path,body]=spec,r=await fetch(`http://127.0.0.1:${env.port}/api${path}`,{method:m,headers:{Authorization:`Bearer ${s.t}`,'Content-Type':'application/json','Idempotency-Key':id},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(15000)}),data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data?.error||`Local action failed (${r.status})`);e.code=data?.code;e.status=r.status;throw e}return data}finally{db.prepare('UPDATE auth_sessions SET revoked_at=?,ended_at=?,end_reason=? WHERE id=? AND revoked_at IS NULL').run(nowIso(),nowIso(),'cloud_admin_action',s.id)}}
export async function executeCloudAdminAction(command){const id=String(command?.id||''),p=command?.payload||{},action=String(p.action||''),args=p.args&&typeof p.args==='object'?p.args:{};const old=db.prepare('SELECT status,result FROM cloud_admin_actions WHERE cloud_command_id=?').get(id);if(old?.status==='completed')return{ok:true,result:JSON.parse(old.result||'{}')};if(old?.status==='failed')return{ok:false,result:JSON.parse(old.result||'{}')};if(!A[action])return{ok:false,result:{error:'Unsupported cloud Admin action.',code:'INVALID_ACTION'}};db.prepare("INSERT OR IGNORE INTO cloud_admin_actions(cloud_command_id,action,status,created_at) VALUES(?,?,'running',?)").run(id,action,nowIso());try{const result=await call(A[action](args),id);db.prepare("UPDATE cloud_admin_actions SET status='completed',result=?,completed_at=? WHERE cloud_command_id=?").run(JSON.stringify(result||{}),nowIso(),id);return{ok:true,result}}catch(e){const result={error:e.message,code:e.code||'ACTION_FAILED',status:e.status||500};db.prepare("UPDATE cloud_admin_actions SET status='failed',result=?,completed_at=? WHERE cloud_command_id=?").run(JSON.stringify(result),nowIso(),id);return{ok:false,result}}}
