import { db, nowIso } from '../db/connection.js'
export function getCloudIdentity(){return db.prepare(`SELECT organization_id,branch_id,edge_id,edge_token,cloud_url,realtime_topic_key,paired_at,last_seen_at,config_version,metadata FROM cloud_identity WHERE id=1`).get()||null}
export function saveCloudIdentity(identity){const now=nowIso();db.prepare(`INSERT INTO cloud_identity(id,organization_id,branch_id,edge_id,edge_token,cloud_url,realtime_topic_key,paired_at,last_seen_at,config_version,metadata) VALUES(1,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET organization_id=excluded.organization_id,branch_id=excluded.branch_id,edge_id=excluded.edge_id,edge_token=excluded.edge_token,cloud_url=excluded.cloud_url,realtime_topic_key=excluded.realtime_topic_key,paired_at=excluded.paired_at,last_seen_at=excluded.last_seen_at,config_version=excluded.config_version,metadata=excluded.metadata`).run(identity.organizationId,identity.branchId,identity.edgeId,identity.edgeToken,identity.supabaseUrl,identity.realtimeTopicKey||null,identity.pairedAt||now,identity.lastSeenAt||null,Number(identity.configVersion||0),JSON.stringify(identity.metadata||{}));return getCloudIdentity()}
export function clearCloudIdentity(){db.transaction(()=>{db.prepare('DELETE FROM sync_outbox WHERE synced_at IS NULL').run();db.prepare('DELETE FROM cloud_identity WHERE id=1').run();db.prepare('DELETE FROM cloud_branch_config WHERE id=1').run()})()}
export function touchCloudSeen(at=nowIso()){db.prepare('UPDATE cloud_identity SET last_seen_at=? WHERE id=1').run(at)}
export function saveCloudBranchConfig(version,config){const now=nowIso();db.prepare(`INSERT INTO cloud_branch_config(id,version,config_json,updated_at) VALUES(1,?,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,config_json=excluded.config_json,updated_at=excluded.updated_at`).run(Number(version||0),JSON.stringify(config||{}),now);db.prepare('UPDATE cloud_identity SET config_version=? WHERE id=1').run(Number(version||0))}
export function getCloudBranchConfig(){const r=db.prepare('SELECT version,config_json,updated_at FROM cloud_branch_config WHERE id=1').get();if(!r)return{version:0,config:{},updatedAt:null};let config={};try{config=JSON.parse(r.config_json||'{}')}catch{}return{version:Number(r.version||0),config,updatedAt:r.updated_at||null}}
export function setSyncState(key,value){db.prepare('INSERT OR REPLACE INTO sync_state(key,value,updated_at) VALUES(?,?,?)').run(key,String(value??''),nowIso())}
export function getSyncState(key){return db.prepare('SELECT value,updated_at FROM sync_state WHERE key=?').get(key)||null}
export function setCloudLicense(value){setSyncState('cloud_license',JSON.stringify(value||{}))}
export function getCloudLicense(){try{return JSON.parse(getSyncState('cloud_license')?.value||'{}')}catch{return{}}}
export function getSyncSummary(){const pending=db.prepare('SELECT COUNT(*) c FROM sync_outbox WHERE synced_at IS NULL').get()?.c||0,failed=db.prepare("SELECT COUNT(*) c FROM sync_outbox WHERE synced_at IS NULL AND last_error IS NOT NULL").get()?.c||0,lastSyncedAt=db.prepare('SELECT MAX(synced_at) at FROM sync_outbox').get()?.at||null;return{pending:Number(pending),failed:Number(failed),lastSyncedAt,lastSuccessAt:getSyncState('cloud_last_success_at')?.value||null,lastError:getSyncState('cloud_last_error')?.value||null}}
