import { createClient, type SupabaseClient } from 'npm:@supabase/supabase-js@2'

const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-aezakmi-edge-id, x-aezakmi-edge-token','Access-Control-Allow-Methods':'POST,OPTIONS'}
function preflight(req:Request){if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});return null}
function json(value:unknown,status=200){return new Response(JSON.stringify(value),{status,headers:{...corsHeaders,'Content-Type':'application/json'}})}
function fail(error:any,fallback='Request failed.'){const status=Number(error?.status||500);return json({success:false,code:error?.code||'SERVER_ERROR',error:status>=500?fallback:(error?.message||fallback)},status)}
async function sha256(value:string){const bytes=new TextEncoder().encode(value);const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')}
function token(bytes=32){const v=new Uint8Array(bytes);crypto.getRandomValues(v);return btoa(String.fromCharCode(...v)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function namedKey(envName:string){const raw=Deno.env.get(envName)||'';if(!raw)return'';try{const parsed=JSON.parse(raw);if(parsed&&typeof parsed==='object')return String(parsed.default||Object.values(parsed)[0]||'')}catch{}return''}
function projectUrl(){const value=Deno.env.get('SUPABASE_URL')||'';if(!value)throw Object.assign(new Error('SUPABASE_URL unavailable.'),{status:500});return value.replace(/\/+$/,'')}
function publishableKey(){return Deno.env.get('SUPABASE_PUBLISHABLE_KEY')||namedKey('SUPABASE_PUBLISHABLE_KEYS')||Deno.env.get('SUPABASE_ANON_KEY')||''}
function secretKey(){const value=Deno.env.get('SUPABASE_SECRET_KEY')||namedKey('SUPABASE_SECRET_KEYS')||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!value)throw Object.assign(new Error('Supabase privileged key is unavailable in this Edge Function.'),{status:500});return value}
function adminClient():SupabaseClient{return createClient(projectUrl(),secretKey(),{auth:{persistSession:false,autoRefreshToken:false}})}
async function userClient(req:Request){const authorization=req.headers.get('authorization')||'';if(!authorization.startsWith('Bearer '))throw Object.assign(new Error('Sign in first.'),{status:401,code:'AUTH_REQUIRED'});const key=publishableKey();if(!key)throw Object.assign(new Error('Supabase publishable key is unavailable in this Edge Function.'),{status:500});const client=createClient(projectUrl(),key,{global:{headers:{Authorization:authorization}},auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await client.auth.getUser();if(error||!data.user)throw Object.assign(new Error('Cloud session invalid.'),{status:401,code:'AUTH_INVALID'});return{client,user:data.user}}
async function requireMembership(admin:SupabaseClient,userId:string,organizationId:string,roles:string[]=[]){const{data,error}=await admin.from('organization_members').select('role').eq('organization_id',organizationId).eq('user_id',userId).maybeSingle();if(error)throw error;if(!data||(roles.length&&!roles.includes(data.role)))throw Object.assign(new Error('Forbidden.'),{status:403,code:'FORBIDDEN'});return data}
async function requireEdge(req:Request,admin:SupabaseClient){const id=(req.headers.get('x-aezakmi-edge-id')||'').trim(),edgeToken=req.headers.get('x-aezakmi-edge-token')||'';if(!id||!edgeToken)throw Object.assign(new Error('Edge credentials required.'),{status:401,code:'EDGE_AUTH_REQUIRED'});const hash=await sha256(edgeToken);const{data,error}=await admin.rpc('aezakmi_verify_edge',{p_edge_id:id,p_token_hash:hash});if(error)throw error;const edge=Array.isArray(data)?data[0]:null;if(!edge)throw Object.assign(new Error('Edge credential invalid or revoked.'),{status:401,code:'EDGE_AUTH_INVALID'});return edge}
async function broadcastWakeup(url:string,secret:string,topicKey:string,payload:Record<string,unknown>={}){if(!topicKey)return;try{await fetch(`${url}/realtime/v1/api/broadcast/${encodeURIComponent(`edge-wakeup:${topicKey}`)}/events/sync`,{method:'POST',headers:{apikey:secret,'Content-Type':'application/json'},body:JSON.stringify(payload)})}catch{}}

Deno.serve(async req=>{const o=preflight(req);if(o)return o;try{const admin=adminClient(),edge=await requireEdge(req,admin),now=new Date().toISOString();await admin.from('edge_servers').update({revoked_at:now,updated_at:now}).eq('id',edge.id);return json({success:true})}catch(e){return fail(e,'Unable to unpair Edge server.')}})
