-- Aezakmi Cloud — Supabase-only multi-tenant control plane.
create extension if not exists pgcrypto;

create table if not exists public.organizations(id uuid primary key default gen_random_uuid(),name text not null check(length(trim(name)) between 2 and 120),slug text not null unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.organization_members(organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role text not null check(role in('owner','admin','manager','viewer')),created_at timestamptz not null default now(),primary key(organization_id,user_id));
create index if not exists organization_members_user_idx on public.organization_members(user_id);
create table if not exists public.branches(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,code text,timezone text not null default 'Asia/Manila',is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,code));
create table if not exists public.branch_configs(branch_id uuid primary key references public.branches(id) on delete cascade,version bigint not null default 1,config jsonb not null default '{}'::jsonb,updated_by uuid references auth.users(id) on delete set null,updated_at timestamptz not null default now());
create table if not exists public.edge_servers(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid not null references public.branches(id) on delete cascade,installation_id uuid not null unique,name text not null default 'Aezakmi Edge',device_token_hash text not null,realtime_topic_key text not null,software_version text,status_snapshot jsonb not null default '{}'::jsonb,paired_at timestamptz not null default now(),last_seen_at timestamptz,last_sync_at timestamptz,revoked_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists edge_servers_branch_idx on public.edge_servers(branch_id);
create table if not exists public.edge_pairing_codes(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid not null references public.branches(id) on delete cascade,code_hash text not null unique,expires_at timestamptz not null,used_at timestamptz,used_by_edge_id uuid references public.edge_servers(id) on delete set null,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table if not exists public.edge_events(id uuid primary key default gen_random_uuid(),event_id text not null,organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid not null references public.edge_servers(id) on delete cascade,event_type text not null,entity_type text,entity_id text,payload jsonb not null default '{}'::jsonb,occurred_at timestamptz not null,received_at timestamptz not null default now(),unique(edge_id,event_id));
create table if not exists public.cloud_commands(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid not null references public.edge_servers(id) on delete cascade,station_id text,command text not null check(command in('lock','unlock','reboot','shutdown','wake','game_update','sync','admin_action','admin_api')),payload jsonb not null default '{}'::jsonb,idempotency_key text,status text not null default 'queued' check(status in('queued','dispatched','running','completed','failed','expired')),requested_by uuid references auth.users(id) on delete set null,requested_at timestamptz not null default now(),expires_at timestamptz not null default(now()+interval '5 minutes'),completed_at timestamptz,result jsonb);
create index if not exists cloud_commands_edge_pending_idx on public.cloud_commands(edge_id,status,requested_at);
create unique index if not exists cloud_commands_idempotency_idx on public.cloud_commands(branch_id,requested_by,idempotency_key);
create table if not exists public.subscriptions(organization_id uuid primary key references public.organizations(id) on delete cascade,plan text not null default 'starter',status text not null default 'trial',max_branches integer not null default 1,max_stations integer not null default 30,trial_ends_at timestamptz default(now()+interval '14 days'),grace_until timestamptz,current_period_end timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.cloud_audit_logs(id uuid primary key default gen_random_uuid(),organization_id uuid references public.organizations(id) on delete cascade,branch_id uuid references public.branches(id) on delete cascade,actor_user_id uuid references auth.users(id) on delete set null,edge_id uuid references public.edge_servers(id) on delete set null,action text not null,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

create table if not exists public.branch_members(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,member_code text,name text,username text,birthdate date,phone text,email text,tier text,wallet_balance numeric not null default 0,session_seconds_remaining bigint not null default 0,status text,pc_id text,pc_ip text,created_at timestamptz,updated_at timestamptz,primary key(branch_id,local_id));
create table if not exists public.branch_stations(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,pc_number text,label text,ip_address text,mac_address text,spec text,status text,created_at timestamptz,updated_at timestamptz,primary key(branch_id,local_id));
create table if not exists public.branch_rate_plans(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,data jsonb not null default '{}'::jsonb,updated_at timestamptz,primary key(branch_id,local_id));
create table if not exists public.branch_sessions(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,member_id text,pc_id text,rate_plan_id text,customer_name text,billing_type text,amount_paid numeric,prepaid_seconds bigint,postpaid_rate_per_minute numeric,started_at timestamptz,expires_at timestamptz,ended_at timestamptz,status text,data jsonb not null default '{}'::jsonb,primary key(branch_id,local_id));
create table if not exists public.branch_wallet_ledger(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,member_id text,type text,amount numeric,balance_before numeric,balance_after numeric,reference_type text,reference_id text,created_at timestamptz,primary key(branch_id,local_id));
create table if not exists public.branch_session_time_ledger(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,type text,member_id text,counterparty_member_id text,computer_session_id text,seconds bigint,reference_id text,created_at timestamptz,primary key(branch_id,local_id));
create table if not exists public.branch_top_ups(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,data jsonb not null default '{}'::jsonb,requested_at timestamptz,primary key(branch_id,local_id));
create table if not exists public.branch_session_extensions(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,data jsonb not null default '{}'::jsonb,requested_at timestamptz,primary key(branch_id,local_id));
create table if not exists public.branch_revenue_events(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,event_type text,source_type text,source_id text,amount_centavos bigint not null default 0,occurred_at timestamptz,category text,payment_method text,member_id text,pc_id text,metadata jsonb,reversed_event_id text,primary key(branch_id,local_id));
create table if not exists public.branch_announcements(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,data jsonb not null default '{}'::jsonb,updated_at timestamptz,primary key(branch_id,local_id));
create table if not exists public.branch_feedback(branch_id uuid not null references public.branches(id) on delete cascade,edge_id uuid references public.edge_servers(id) on delete set null,local_id text not null,data jsonb not null default '{}'::jsonb,created_at timestamptz,primary key(branch_id,local_id));

create or replace function public.aezakmi_is_org_member(target_org uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.organization_members where organization_id=target_org and user_id=auth.uid())$$;
create or replace function public.aezakmi_has_org_role(target_org uuid,allowed_roles text[]) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.organization_members where organization_id=target_org and user_id=auth.uid() and role=any(allowed_roles))$$;

create or replace function public.aezakmi_create_organization(p_name text,p_branch_name text default 'Main Branch') returns table(organization_id uuid,branch_id uuid) language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();oid uuid:=gen_random_uuid();bid uuid:=gen_random_uuid();slug_base text;begin if uid is null then raise exception 'AUTH_REQUIRED';end if;if length(trim(p_name))<2 then raise exception 'ORG_NAME_INVALID';end if;slug_base:=trim(both '-' from regexp_replace(lower(trim(p_name)),'[^a-z0-9]+','-','g'));if length(slug_base)<2 then slug_base:='cafe';end if;insert into organizations(id,name,slug) values(oid,trim(p_name),left(slug_base,50)||'-'||substr(replace(oid::text,'-',''),1,8));insert into organization_members values(oid,uid,'owner',now());insert into subscriptions(organization_id) values(oid);insert into branches(id,organization_id,name) values(bid,oid,trim(p_branch_name));insert into branch_configs(branch_id) values(bid);return query select oid,bid;end$$;
create or replace function public.aezakmi_update_branch_config(p_branch_id uuid,p_config jsonb) returns table(version bigint,config jsonb,updated_at timestamptz) language plpgsql security definer set search_path=public as $$declare uid uuid:=auth.uid();oid uuid;begin select organization_id into oid from branches where id=p_branch_id;if uid is null or not aezakmi_has_org_role(oid,array['owner','admin','manager']) then raise exception 'FORBIDDEN';end if;insert into branch_configs(branch_id,version,config,updated_by,updated_at) values(p_branch_id,1,coalesce(p_config,'{}'),uid,now()) on conflict(branch_id) do update set version=branch_configs.version+1,config=excluded.config,updated_by=uid,updated_at=now();return query select c.version,c.config,c.updated_at from branch_configs c where c.branch_id=p_branch_id;end$$;
create or replace function public.aezakmi_verify_edge(p_edge_id uuid,p_token_hash text) returns table(id uuid,organization_id uuid,branch_id uuid,realtime_topic_key text) language sql security definer set search_path=public as $$select e.id,e.organization_id,e.branch_id,e.realtime_topic_key from edge_servers e where e.id=p_edge_id and e.device_token_hash=p_token_hash and e.revoked_at is null$$;

create or replace function public.aezakmi_ingest_edge_events(p_edge_id uuid,p_events jsonb) returns integer language plpgsql security definer set search_path=public as $$declare e edge_servers%rowtype;item jsonb;payload jsonb;eid text;et text;occurred timestamptz;accepted integer:=0;begin select * into e from edge_servers where id=p_edge_id and revoked_at is null;if not found then raise exception 'EDGE_INVALID';end if;for item in select value from jsonb_array_elements(coalesce(p_events,'[]'::jsonb)) loop eid:=item->>'eventId';et:=item->>'eventType';payload:=coalesce(item->'payload','{}'::jsonb);occurred:=coalesce((item->>'occurredAt')::timestamptz,now());if eid is null or et is null then continue;end if;insert into edge_events(event_id,organization_id,branch_id,edge_id,event_type,entity_type,entity_id,payload,occurred_at) values(eid,e.organization_id,e.branch_id,e.id,et,item->>'entityType',item->>'entityId',payload,occurred) on conflict(edge_id,event_id) do nothing;if not found then continue;end if;accepted:=accepted+1;
if et='member.upsert' then insert into branch_members(branch_id,edge_id,local_id,member_code,name,username,birthdate,phone,email,tier,wallet_balance,session_seconds_remaining,status,pc_id,pc_ip,created_at,updated_at) values(e.branch_id,e.id,payload->>'id',payload->>'member_code',payload->>'name',payload->>'username',nullif(payload->>'birthdate','')::date,payload->>'phone',payload->>'email',payload->>'tier',coalesce((payload->>'wallet_balance')::numeric,0),coalesce((payload->>'session_seconds_remaining')::bigint,0),payload->>'status',payload->>'pc_id',payload->>'pc_ip',nullif(payload->>'created_at','')::timestamptz,nullif(payload->>'updated_at','')::timestamptz) on conflict(branch_id,local_id) do update set member_code=excluded.member_code,name=excluded.name,username=excluded.username,birthdate=excluded.birthdate,phone=excluded.phone,email=excluded.email,tier=excluded.tier,wallet_balance=excluded.wallet_balance,session_seconds_remaining=excluded.session_seconds_remaining,status=excluded.status,pc_id=excluded.pc_id,pc_ip=excluded.pc_ip,updated_at=excluded.updated_at;
elsif et='member.delete' then delete from branch_members where branch_id=e.branch_id and local_id=payload->>'id';
elsif et='station.upsert' then insert into branch_stations(branch_id,edge_id,local_id,pc_number,label,ip_address,mac_address,spec,status,created_at,updated_at) values(e.branch_id,e.id,payload->>'id',payload->>'pc_number',payload->>'label',payload->>'ip_address',payload->>'mac_address',payload->>'spec',payload->>'status',nullif(payload->>'created_at','')::timestamptz,nullif(payload->>'updated_at','')::timestamptz) on conflict(branch_id,local_id) do update set pc_number=excluded.pc_number,label=excluded.label,ip_address=excluded.ip_address,mac_address=excluded.mac_address,spec=excluded.spec,status=excluded.status,updated_at=excluded.updated_at;
elsif et='station.delete' then delete from branch_stations where branch_id=e.branch_id and local_id=payload->>'id';
elsif et='rate_plan.upsert' then insert into branch_rate_plans(branch_id,edge_id,local_id,data,updated_at) values(e.branch_id,e.id,payload->>'id',payload,nullif(payload->>'updated_at','')::timestamptz) on conflict(branch_id,local_id) do update set data=excluded.data,updated_at=excluded.updated_at;
elsif et='rate_plan.delete' then delete from branch_rate_plans where branch_id=e.branch_id and local_id=payload->>'id';
elsif et='session.upsert' then insert into branch_sessions(branch_id,edge_id,local_id,member_id,pc_id,rate_plan_id,customer_name,billing_type,amount_paid,prepaid_seconds,postpaid_rate_per_minute,started_at,expires_at,ended_at,status,data) values(e.branch_id,e.id,payload->>'id',payload->>'member_id',payload->>'pc_id',payload->>'rate_plan_id',payload->>'customer_name',payload->>'billing_type',nullif(payload->>'amount_paid','')::numeric,nullif(payload->>'prepaid_seconds','')::bigint,nullif(payload->>'postpaid_rate_per_minute','')::numeric,nullif(payload->>'started_at','')::timestamptz,nullif(payload->>'expires_at','')::timestamptz,nullif(payload->>'ended_at','')::timestamptz,payload->>'status',payload) on conflict(branch_id,local_id) do update set member_id=excluded.member_id,pc_id=excluded.pc_id,rate_plan_id=excluded.rate_plan_id,customer_name=excluded.customer_name,billing_type=excluded.billing_type,amount_paid=excluded.amount_paid,prepaid_seconds=excluded.prepaid_seconds,postpaid_rate_per_minute=excluded.postpaid_rate_per_minute,started_at=excluded.started_at,expires_at=excluded.expires_at,ended_at=excluded.ended_at,status=excluded.status,data=excluded.data;
elsif et='wallet_ledger.insert' then insert into branch_wallet_ledger(branch_id,edge_id,local_id,member_id,type,amount,balance_before,balance_after,reference_type,reference_id,created_at) values(e.branch_id,e.id,payload->>'id',payload->>'member_id',payload->>'type',coalesce((payload->>'amount')::numeric,0),nullif(payload->>'balance_before','')::numeric,nullif(payload->>'balance_after','')::numeric,payload->>'reference_type',payload->>'reference_id',nullif(payload->>'created_at','')::timestamptz) on conflict do nothing;
elsif et='session_time_ledger.insert' then insert into branch_session_time_ledger(branch_id,edge_id,local_id,type,member_id,counterparty_member_id,computer_session_id,seconds,reference_id,created_at) values(e.branch_id,e.id,payload->>'id',payload->>'type',payload->>'member_id',payload->>'counterparty_member_id',payload->>'computer_session_id',coalesce((payload->>'seconds')::bigint,0),payload->>'reference_id',nullif(payload->>'created_at','')::timestamptz) on conflict do nothing;
elsif et='top_up.upsert' then insert into branch_top_ups(branch_id,edge_id,local_id,data,requested_at) values(e.branch_id,e.id,payload->>'id',payload,nullif(payload->>'requested_at','')::timestamptz) on conflict(branch_id,local_id) do update set data=excluded.data,requested_at=excluded.requested_at;
elsif et='session_extension.upsert' then insert into branch_session_extensions(branch_id,edge_id,local_id,data,requested_at) values(e.branch_id,e.id,payload->>'id',payload,nullif(payload->>'requested_at','')::timestamptz) on conflict(branch_id,local_id) do update set data=excluded.data,requested_at=excluded.requested_at;
elsif et='revenue.insert' then insert into branch_revenue_events(branch_id,edge_id,local_id,event_type,source_type,source_id,amount_centavos,occurred_at,category,payment_method,member_id,pc_id,metadata,reversed_event_id) values(e.branch_id,e.id,payload->>'id',payload->>'event_type',payload->>'source_type',payload->>'source_id',coalesce((payload->>'amount_centavos')::bigint,0),nullif(payload->>'occurred_at','')::timestamptz,payload->>'category',payload->>'payment_method',payload->>'member_id',payload->>'pc_id',case when jsonb_typeof(payload->'metadata')='object' then payload->'metadata' else '{}' end,payload->>'reversed_event_id') on conflict do nothing;
elsif et='announcement.upsert' then insert into branch_announcements(branch_id,edge_id,local_id,data,updated_at) values(e.branch_id,e.id,payload->>'id',payload,nullif(payload->>'updated_at','')::timestamptz) on conflict(branch_id,local_id) do update set data=excluded.data,updated_at=excluded.updated_at;
elsif et='announcement.delete' then delete from branch_announcements where branch_id=e.branch_id and local_id=payload->>'id';
elsif et='feedback.upsert' then insert into branch_feedback(branch_id,edge_id,local_id,data,created_at) values(e.branch_id,e.id,payload->>'id',payload,nullif(payload->>'created_at','')::timestamptz) on conflict(branch_id,local_id) do update set data=excluded.data;
end if;end loop;return accepted;end$$;

-- RLS: signed-in users only see organizations they belong to.
do $$declare t text;begin foreach t in array array['organizations','organization_members','branches','branch_configs','edge_servers','edge_pairing_codes','edge_events','cloud_commands','subscriptions','cloud_audit_logs','branch_members','branch_stations','branch_rate_plans','branch_sessions','branch_wallet_ledger','branch_session_time_ledger','branch_top_ups','branch_session_extensions','branch_revenue_events','branch_announcements','branch_feedback'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy organizations_read on organizations for select to authenticated using(aezakmi_is_org_member(id));
create policy org_members_read on organization_members for select to authenticated using(aezakmi_is_org_member(organization_id));
create policy branches_read on branches for select to authenticated using(aezakmi_is_org_member(organization_id));
create policy branch_configs_read on branch_configs for select to authenticated using(exists(select 1 from branches b where b.id=branch_id and aezakmi_is_org_member(b.organization_id)));
create policy edge_servers_read on edge_servers for select to authenticated using(aezakmi_is_org_member(organization_id));
create policy edge_events_read on edge_events for select to authenticated using(aezakmi_is_org_member(organization_id));
create policy cloud_commands_read on cloud_commands for select to authenticated using(aezakmi_is_org_member(organization_id));
create policy subscriptions_read on subscriptions for select to authenticated using(aezakmi_is_org_member(organization_id));
create policy audit_read on cloud_audit_logs for select to authenticated using(aezakmi_has_org_role(organization_id,array['owner','admin','manager']));
do $$declare t text;begin foreach t in array array['branch_members','branch_stations','branch_rate_plans','branch_sessions','branch_wallet_ledger','branch_session_time_ledger','branch_top_ups','branch_session_extensions','branch_revenue_events','branch_announcements','branch_feedback'] loop execute format('create policy %I on public.%I for select to authenticated using(exists(select 1 from public.branches b where b.id=branch_id and public.aezakmi_is_org_member(b.organization_id)))',t||'_read',t);end loop;end$$;

-- Pairing codes contain credential-equivalent one-time secrets and are Edge-Function-only.
alter table public.edge_pairing_codes enable row level security;
revoke all on table public.edge_pairing_codes from public, anon, authenticated;
grant select,insert,update,delete on table public.edge_pairing_codes to service_role;

grant select on organizations,organization_members,branches,branch_configs,edge_servers,edge_events,cloud_commands,subscriptions,cloud_audit_logs,branch_members,branch_stations,branch_rate_plans,branch_sessions,branch_wallet_ledger,branch_session_time_ledger,branch_top_ups,branch_session_extensions,branch_revenue_events,branch_announcements,branch_feedback to authenticated;
grant execute on function aezakmi_create_organization(text,text),aezakmi_update_branch_config(uuid,jsonb) to authenticated;


-- Privileged Edge RPCs are callable only by the server-side service role used by Edge Functions.
revoke all on function public.aezakmi_verify_edge(uuid,text) from public, anon, authenticated;
revoke all on function public.aezakmi_ingest_edge_events(uuid,jsonb) from public, anon, authenticated;
grant execute on function public.aezakmi_verify_edge(uuid,text) to service_role;
grant execute on function public.aezakmi_ingest_edge_events(uuid,jsonb) to service_role;
revoke all on function public.aezakmi_create_organization(text,text) from public, anon;
revoke all on function public.aezakmi_update_branch_config(uuid,jsonb) from public, anon;
grant execute on function public.aezakmi_create_organization(text,text), public.aezakmi_update_branch_config(uuid,jsonb) to authenticated;
